Blog/Controllers/CommentaryController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Attributes;
using Blog.Misc;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;

namespace Blog.Controllers
{
    [Authorize]
    public class CommentaryController : ControllerBase
    {
        public const int MAX_COMMENTARY_LENGTH = 500;
        public const int MIN_COMMENTARY_LENGTH = 10;
        public const int MIN_EDIT_REASON_LENGTH = 10;
        public const int MAX_EDIT_REASON_LENGTH = 100;

        public CommentaryController(ServiceLocator serviceProvider) : base(serviceProvider)
        {

        }

        [HttpGet, AJAX]
        public async Task<IActionResult> GetCommentaryEditAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var commentary = await S.Db.Commentaries.AsNoTracking()
                    .Include(c => c.Author)
                    .FirstOrDefaultAsync(c => c.Id == id);
                var model = new CommentaryEditinigModel()
                {
                    Author = commentary.Author.UserName,
                    AuthorId = commentary.Author.Id,
                    Body = commentary.Body,
                    CommentaryId = commentary.Id,
                };

                return PartialView(Partials.COMMENTARY_EDIT, model);
            }
            else
            {
                throw new Exception();
            }
        }

        [HttpPost, AJAX]
        public async Task<IActionResult> UpdateCommentaryAsync([Required]CommentaryEditinigModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await S.UserManager.GetUserAsync(User);
                var commentary = await S.Db.Commentaries
                    .Include(c => c.Post)
                    .FirstOrDefaultAsync(c => c.Id == model.CommentaryId);
                await S.Permissions.ValidateEditCommentaryAsync(commentary);

                var user = await S.UserManager.GetUserAsync(User);
                commentary.Body = model.Body;
                commentary.Edits.Add(new CommentaryEdit(user, model.Reason, DateTime.UtcNow));
                await S.Repository.AddUserActionAsync(currentUser, new UserAction(ActionType.COMMENTARY_EDIT, commentary));
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(commentary.Post.Id);
            }
            else
            {
                if (model.Reason == null)
                {
                    LayoutModel.AddMessage("Edit reason is required");
                }
                else if (model.Body == null)
                {
                    LayoutModel.AddMessage("Commentary body is required");
                }
                else
                {
                    throw new Exception();
                }
            }

            return Redirect(S.History.GetLastURL());
        }

        [HttpGet, AJAX]
        public async Task<IActionResult> DeleteCommentaryAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var commentary = await S.Db.Commentaries
                    .Include(c => c.Post)
                    .FirstOrDefaultAsync(c => c.Id == id);
                await S.Permissions.ValidateDeleteCommentaryAsync(commentary);
               
                var user = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.COMMENTARY_DELETE, commentary));
                commentary.IsDeleted = true;
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(commentary.Post.Id);

                return Redirect(S.History.GetLastURL());
            }
            else
            {
                throw new Exception();
            }
        }

        [HttpGet, AJAX]
        public async Task<IActionResult> RestoreCommentaryAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var commentary = await S.Db.Commentaries
                    .Include(c => c.Post)
                    .FirstOrDefaultAsync(c => c.Id == id);
                await S.Permissions.ValidateRestoreCommentaryAsync(commentary);
               
                var user = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.COMMENTARY_RESTORED, commentary));
                commentary.IsDeleted = false;
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(commentary.Post.Id);

                return Redirect(S.History.GetLastURL());
            }
            else
            {
                throw new Exception();
            }
        }
    }
}

Blog/Pages/Commentary.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Blog.Pages
{
    public class CommentaryModel : PageModelBase
    {
        public Models.CommentaryModel Commentary { get; private set; }

        public CommentaryModel(ServiceLocator services) : base(services)
        {

        }

        public async Task<IActionResult> OnGetAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var query = await S.Repository.GetCommentaryModelsAsync(
                    S.Db.Commentaries
                    .AsNoTracking()
                    .Where(c => c.Id == id));
                Commentary = query.SingleOrDefault();

                if (Commentary == null)
                {
                    throw new NotFoundException();
                }
                else
                {
                    return Page();
                }
            }
            else
            {
                return Redirect(S.History.GetLastURL());
            }
        }
    }
}

Blog/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Attributes;
using Blog.Middlewares;
using Blog.Middlewares.CachingMiddleware.Policies;
using Blog.Misc;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Utilities.Extensions;

namespace Blog.Pages
{
    public class IndexModel : PageModelBase
    {
        public const int NUM_OF_POSTS_ON_PAGE = 3;

        public List<PostIndexModel> Posts { get; private set; }
        public int NumOfPages { get; private set; }
        public int CurrentPage { get; private set; }
        public string SearchQuery { get; private set; }
        public int NumOfSearchResults { get; private set; }

        public IndexModel(ServiceLocator serviceProvider) : base(serviceProvider)
        {

        }

        [ServerResponseCache(1 * 3600, CachePolicy.UNAUTHENTICATED_USER_SCOPED, CacheManagerService.INDEX_GET_CACHE_KEY)]
        public async Task<IActionResult> OnGetAsync(int? pageIndex)
        {
            return await OnGetFilteredAsync(pageIndex, null);
        }

        public async Task<IActionResult> OnGetFilteredAsync(int? pageIndex, string filter)
        {
            CurrentPage = pageIndex ?? 0;

            var viewablePosts = S.Db.Posts.AsNoTracking()
                .Where(p => p.ModerationInfo.State == ModerationState.MODERATED && !p.IsDeleted);

            if (filter != null)
            {
                var keyword = filter.Split(" ").FirstElementOrDefault("");
                viewablePosts = viewablePosts.Where(p => p.Title.Contains(keyword));
                SearchQuery = filter;
                NumOfSearchResults = await viewablePosts.CountAsync();
                NumOfPages = NumOfSearchResults / NUM_OF_POSTS_ON_PAGE + ((NumOfSearchResults % NUM_OF_POSTS_ON_PAGE == 0) ? 0 : 1);
            }

            Posts = await viewablePosts.OrderByDescending(p => p.CreationTime)
                .Skip(CurrentPage * NUM_OF_POSTS_ON_PAGE)
                .Take(NUM_OF_POSTS_ON_PAGE)
                .Select(p => new PostIndexModel()
                {
                    Author = p.Author.UserName,
                    AuthorId = p.Author.Id,
                    BodyPreview = p.BodyPreview,
                    CreationTime = p.CreationTime,
                    PostId = p.Id,
                    Title = p.Title
                }).ToListAsync();

            if (filter == null)
            {
                NumOfPages = await viewablePosts.CountAsync();
                NumOfPages = NumOfPages / NUM_OF_POSTS_ON_PAGE + ((NumOfPages % NUM_OF_POSTS_ON_PAGE == 0) ? 0 : 1);
            }

            if (Posts.Count == 0 && CurrentPage != 0)
            {
                return RedirectToPage(new { pageIndex = 0 });
            }
            else
            {
                return Page();
            }
        }
    }
}

Blog/Pages/Shared/_Anchor.cshtml
@model Blog.Models.AnchorModel

@{
    var routeData = new Dictionary<string, string>();
    routeData.Add(Model.RouteIdParameterName, Model.RouteId?.ToString());
}

@if (Model.IsShown)
{
    @if (Model.Controller != null)
    {
        <span>| <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-all-route-data=routeData>@Model.Text</a></span>
    }
    else
    {
        if (Model.Handler == null)
        {
            <span>| <a asp-page="@Model.Page" asp-all-route-data=routeData>@Model.Text</a></span>
        }
        else
        {
            <span>| <a asp-page="@Model.Page" asp-page-handler="@Model.Handler" asp-all-route-data=routeData>@Model.Text</a></span>
        }
    }
}

Blog/Pages/Shared/_CommentartyScripts.cshtml
<script>
    $(document).ready(function () {
        var commentaries = $(".commentary-container");
        for (var i = 0; i < commentaries.length; i++) {
            var container = commentaries[i];
            var id = container.getAttribute("id").split("-")[1];
            loadCommentary(container, id);
        }
    });

    function loadCommentary(container, commentaryId) {
        $(".commentary-edit-button", container).click(function () {
            makeRequest('/Commentary/GetCommentaryEditAsync?id=' + commentaryId, "get", function (response) {
                var editViewContainer = $(".commentary-edit-view", container).removeClass("d-none").html(response).show();
                $.validator.unobtrusive.parse(editViewContainer); 
                var commentaryView = $(".commentary-view", container).hide();

                $(".commentary-edit-exit-button", editViewContainer).click(function () {
                    editViewContainer.hide();
                    editViewContainer.html("");
                    commentaryView.show();
                });
            });
        });
    }

    @{
        var target = new ControllerAction(nameof(ReportingController), nameof(ReportingController.ReportCommentaryAsync));
    }

    function reportCommentary(element, id) {
        report(element, "@target.GetURI()", id);
    }
</script>

Blog/Pages/Shared/_Commentary.cshtml
@model Blog.Models.CommentaryModel

    <div id="commentary-@Model.CommentaryId" class="my-4 commentary-container">
        <div class="d-none commentary-edit-view"></div>
        <div class="commentary-view">
            <div class="d-flex flex-row">
                <div class="d-flex flex-column align-self-center mr-4">
                    <partial name="@Partials.PROFILE_IMAGE" model="Model.AuthorProfileImage" />
                </div>
                <div class="d-flex flex-column w-100">
                    <div class="d-flex flex-row justify-content-between">
                        <div class="d-flex flex-column">
                            <h4 id="#@Model.CommentaryId" class="font-weight-normal">
                                <a asp-page="/Commentary" asp-route-id="@Model.CommentaryId">#@Model.CommentaryId</a>
                                <a asp-page="/Account/Profile" asp-route-id="@Model.AuthorId">@Model.Author</a>
                                <span include-if="Model.Permissions.CanEdit">| <a href="" class="no-redirect commentary-edit-button">Edit</a></span>
                                <span include-if="Model.Permissions.CanReport" class="btn-report">| <a class="no-redirect" href="" onclick="reportCommentary(this, @Model.CommentaryId)">Report</a></span>
                                <span include-if="Model.Permissions.CanReportViolation">| <a class="" asp-page="/ViolationReport" asp-page-handler="Commentary" asp-route-id="@Model.CommentaryId">Report violation</a></span>
                                <span include-if="Model.Permissions.CanDelete">| <a class="operation-danger" asp-controller="@nameof(CommentaryController).GetController()" asp-action="@nameof(CommentaryController.DeleteCommentaryAsync)" asp-route-id="@Model.CommentaryId">Delete</a></span>
                                <span include-if="Model.Permissions.CanRestore">| <a class="operation-primary" asp-controller="@nameof(CommentaryController).GetController()" asp-action="@nameof(CommentaryController.RestoreCommentaryAsync)" asp-route-id="@Model.CommentaryId">Restore</a></span>
                            </h4>
                        </div>
                        <div class="d-none d-md-flex flex-column">
                            <h4 class="text-right font-weight-normal">@Model.CreationTime.ToString("hh:mm dd.MM.yyyy")</h4>
                        </div>
                    </div>

                    <div class="d-flex flex-row">
                        <div class="d-flex flex-column text-justify">
                            @if (!Model.IsDeleted)
                            {
                                @if (Model.IsHidden)
                                {
                                    <span class="comment-hidden">@Model.Body</span>
                                }
                                else
                                {
                                    <span>@Model.Body</span>
                                }

                                <div class="mt-1">
                                    @foreach (var edit in Model.Edits)
                                    {
                                        <div>
                                            <span>Edited at @edit.Time.ToString("hh:mm dd.MM.yy") by <a asp-page="/Account/Profile" asp-route-id="@edit.AuthorId">@edit.Author</a></span>
                                            @if (edit.Reason.IsNotNullOrWhiteSpace())
                                            {
                                                <span>Reason: @edit.Reason</span>
                                            }
                                        </div>
                                    }
                                </div>
                            }
                            else
                            {
                                <span class="comment-deleted">The commentary has been deleted</span>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Blog/Pages/Shared/_CommentaryEdit.cshtml
@model CommentaryEditinigModel

<form asp-controller="Commentary" asp-action="UpdateCommentaryAsync" class="form" method="post" style="margin-bottom:20px">
    <input type="hidden" asp-for="CommentaryId"/>

    <h4>
        <a asp-page="/Commentary" asp-route-id="@Model.CommentaryId">#@Model.CommentaryId</a>
        <a asp-page="/Account/Profile" asp-route-id="@Model.AuthorId">@Model.Author</a>
        <button style="display:none;" id="save-@Model.CommentaryId" type="submit" class="commentary-edit-save-button">Save</button>
        <button style="display:none;" id="cancel-@Model.CommentaryId" type="button" class="commentary-edit-exit-button">Cancel</button>
        <span>| <a onclick="$('#save-@Model.CommentaryId').trigger('click')" class="no-redirect operation-primary" href="#">Save</a></span>
        <span>| <a onclick="$('#cancel-@Model.CommentaryId').trigger('click')" class="no-redirect" href="#">Cancel</a></span>
    </h4>

    <div class="d-flex flex-row">
        <div class="d-flex w-100 flex-column">
            <div class="form-group">
                <label>New commentary body</label>
                <textarea class="form-control" asp-for="Body"></textarea>
                <span class="text-danger" asp-validation-for="Body"></span>
            </div>

            <div class="form-group">
                <label>Edit reason</label>
                <input class="form-control" type="text" asp-for="Reason" placeholder="Edit reason" />
                <span class="text-danger" asp-validation-for="Reason"></span>
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
    </div>
</form>

Blog/Pages/Shared/_CommentarySection.cshtml
@model CommentarySectionModel

@foreach (var commentaryModel in Model.Commentaries)
{
    <partial name="@Partials.COMMENTARY" model="commentaryModel" />
}

Blog/Pages/Shared/_DataTableScripts.cshtml
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

<script>
    $(document).ready(function () {
        $('.data-table').DataTable();
    });
</script>

Blog/Pages/Shared/_EntityToCheck.cshtml
@model IEntityToCheck

@{
    var dT = DateTime.UtcNow - Model.AddTime;
}

@if (Model.IsResolved)
{
    <span>
        Resolved @((DateTime.UtcNow - Model.ResolvingTime.Value).ToCurrentTimeRelativeString()), added @dT.ToCurrentTimeRelativeString(), check reason: @Model.CheckReason, check object:
        @{ await Html.RenderPartialAsync("_ObjectReference", new ObjectReferenceModel(Model.Entity)); }
    </span>
}
else
{
    <span>
        Added @dT.ToCurrentTimeRelativeString(), check reason: @Model.CheckReason, check object:
        @{ await Html.RenderPartialAsync("_ObjectReference", new ObjectReferenceModel(Model.Entity)); }
    </span>
}

Blog/Pages/Shared/_IndexPageButton.cshtml
@model IndexPageButtonModel

@if (Model.SearhQuery == null)
{
    <a class="page-link" asp-page="/Index" asp-route-pageIndex="@Model.PageIndex">@Html.Raw(Model.Content)</a>
}
else
{
    <a class="page-link" asp-page="/Index" asp-page-handler="Filtered" asp-route-filter="@Model.SearhQuery" asp-route-pageIndex="@Model.PageIndex">@Html.Raw(Model.Content)</a>
}

Blog/Pages/Shared/_Layout.cshtml
@model ILayoutModelProvider

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap-4.3.1-dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    @*<link rel="stylesheet" href="~/ js / tinymce /skins/ui/oxide/content.min.css" />*@
    @*<link rel="stylesheet" href="~/js/tinymce/skins/content/default/content.min.css" />*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" />

    @RenderSection("Styles", required: false)

    <title>@ViewData["Title"]</title>

    <script>
        var partialLoaders = [];
    </script>
</head>

<body>
    <div>
        <div id="busyModal" class="modal">
            <div class="modal-content">
                <p id="busyModalTextContainer" align="center"></p>
            </div>
        </div>

        <nav class="navbar navbar-expand-md navbar-light bg-white">
            <a class="navbar-brand" asp-page="/Index">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav mr-auto">
                    <li include-if="Model.LayoutModel.UserName != null" class="nav-item">
                        <a class="nav-link" asp-page="/Account/Profile">@Model.LayoutModel.UserName</a>
                    </li>
                    <li include-if="Model.LayoutModel.UserName != null" class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                    </li>

                    <li include-if="Model.LayoutModel.UserName == null" class="nav-item">
                        <a class="nav-link" asp-page="/Account/Login">Login</a>
                    </li>
                    <li include-if="Model.LayoutModel.UserName == null" class="nav-item">
                        <a class="nav-link" asp-page="/Account/Register">Register</a>
                    </li>

                    <li include-if="Model.LayoutModel.CanCreatePost" class="nav-item">
                        <a class="nav-link" asp-page="/PostCreate">New post</a>
                    </li>

                    <li include-if="Model.LayoutModel.CanAccessModsPanel" class="nav-item">
                        <a class="nav-link" asp-page="/ModeratorPanel">Moderator panel</a>
                    </li>

                    <li include-if="Model.LayoutModel.CanAccessAdminsPanel" class="nav-item">
                        <a class="nav-link" asp-page="/AdminPanel">Admin panel</a>
                    </li>
                </ul>

                <form class="form-inline my-2" method="get" action="@SearchController.SEARCH_URI">
                    <div class="input-group">
                        <input name="query" class="form-control mr-2" type="search" placeholder="Search" aria-label="Search" />
                        <button class="btn btn-light" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </nav>

        <div class="d-none">
            <div id="message-template">
                <div class="message container-fluid">
                    <div class="row justify-content-center py-3">
                        <div class="col container-main">
                            <div class="d-flex flex-sm-row d-flex">
                                <div class="message-text d-flex flex-sm-column flex-grow-1">

                                </div>

                                <div class="d-flex flex-sm-column align-self-center ml-2">
                                    <a href="" class="no-redirect" onclick="removeParent(this)">Dismiss</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="message-button-template">
                <div class="d-flex flex-sm-column align-self-center ml-2">
                    <span><a href="" class="no-redirect message-button"></a> |</span>
                </div>
            </div>
        </div>
        <div id="messages"></div>

        @RenderBody()

        <footer>
            <span>Created by <a href="https://github.com/GataullinRR">GataullinRR</a></span>
            <span style="float:right">Powered by ASP .NET Core 2.2</span>
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <partial name="_JQuery" />
        <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" type="text/javascript"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" type="text/javascript"></script>
        <script src="~/lib/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>
        <script src="~/js/tinymce/tinymce.min.js"></script>
        <script src="~/js/site.js"></script>

        <script>
                // See https://www.tiny.cloud/docs/demo/full-featured/
                // and https://www.tiny.cloud/docs/configure/editor-appearance/#menu
            tinymce.init({
                mode: "specific_textareas",
                editor_selector: "rich-edit",
                plugins: 'preview paste searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen table image link codesample charmap hr pagebreak nonbreaking anchor insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
                imagetools_cors_hosts: ['picsum.photos'],
                toolbar: 'undo redo | bold italic underline strikethrough | outdent indent |  numlist bullist | removeformat | charmap emoticons | fullscreen preview | insertfile image media link anchor codesample',
                toolbar_sticky: true,
                autosave_ask_before_unload: true,
                autosave_interval: "30s",
                autosave_prefix: "{path}{query}-{id}-",
                autosave_restore_when_empty: false,
                autosave_retention: "10m",
                image_advtab: true,
                importcss_append: true,
                height: 400,
                height: 600,
                image_caption: true,
                quickbars_selection_toolbar: 'bold italic underline strikethrough | quicklink blockquote quickimage quicktable',
                noneditable_noneditable_class: "mceNonEditable",
                toolbar_drawer: 'sliding',
                contextmenu: "link image imagetools",
                menu: {
                    file: { title: 'File', items: 'newdocument restoredraft | preview | print ' },
                    edit: { title: 'Edit', items: 'undo redo | cut copy paste | selectall | searchreplace' },
                    view: { title: 'View', items: 'code | visualaid visualchars visualblocks | spellchecker | preview fullscreen' },
                    insert: { title: 'Insert', items: 'image link media codesample inserttable | charmap emoticons hr | anchor toc | insertdatetime' },
                    format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript | removeformat' },
                    tools: { title: 'Tools', items: 'code wordcount' },
                    table: { title: 'Table', items: 'inserttable tableprops deletetable row column cell' },
                    help: { title: 'Help', items: '' }
                }
            });

            $(document).ready(function () {

                function applyClasses() {
                    $('a').click(function (e) {
                        if ($(this).hasClass("no-redirect")) {
                            e.preventDefault();
                        }
                        else {

                        }
                    });
                }

                var observer = new MutationObserver(function (mutations) {

                    mutations.forEach(function (mutation) {
                        if (mutation.addedNodes && mutation.addedNodes.length > 0) {

                            applyClasses();
                        }
                    });
                });

                var config = {
                    attributes: true,
                    childList: true,
                    characterData: true,
                    subtree: true, // Important
                };

                @foreach (var message in Model.LayoutModel.Messages)
                {
                    var actions = message.JSActions.Select(a => $"{a.Name}=>{a.FunctionName}").Aggregate(",");
                    <text>renderMessage("@message.Text", "@actions");</text>
                }
                observer.observe(document.body, config);
                applyClasses();

                for (var i = 0; i < partialLoaders.length; i++) {
                    partialLoaders[i]();
                }
            });

                function showBusy(operationName) {
                    var modal = document.getElementById("busyModal");
                    var modalTextContainer = document.getElementById("busyModalTextContainer");
                    modalTextContainer.innerHTML = operationName;
                    modal.style.display = "block";

                    return function () {
                        modal.style.display = "none";
                    }
                }

                function renderMessage(messageText, jsActions) {
                    var template = $($("#message-template").html());
                    $(".message-text", template).html(messageText);
                    if (jsActions !== undefined) {
                        jsActions = jsActions.split(',');
                        for (var i = 0; i < jsActions.length; i++) {
                            var jsAction = jsActions[i];
                            var nameAndFunc = jsAction.split('=>');

                            var buttonTemplate = $($("#message-button-template").html());
                            $("a", buttonTemplate).html(nameAndFunc[0]).attr("onclick", nameAndFunc[1]);
                            $(buttonTemplate).insertAfter($(".message-text", template));
                        }
                    }
                    $("#messages").append(template);
                }

                function removeParent(element) {
                    var message = element.parentElement.closest(".message");
                    message.parentElement.removeChild(message);

                    return true;
                }

                function report(element, route, id) {
                    makePost(route, { "id": id }, true,
                        function () {
                            renderMessage("Report has been submitted");
                            var reportButton = element.parentElement.closest(".btn-report");
                            reportButton.parentElement.removeChild(reportButton);
                        },
                        reportError
                    );

                    function reportError() {
                        renderMessage("An error occurred during submitting the report :(");
                    }
                }
        </script>

        @RenderSection("Scripts", required: false)

        <script>
            $(document).ready(function () {
                var widgets = $("div.widget");
                for (var i = 0; i < widgets.length; i++) {
                    var loader = $(widgets[i]).attr("widget-loader");
                    try {
                        eval(loader.toString() + "();");
                    }
                    catch (ex) {
                        console.error("Error while executing widget loader with name: " + loader + " ex: " + ex);
                    }
                }
            });
        </script>
    </div>
</body>
</html>

Blog/Pages/Shared/_LinkToUser.cshtml
@model User

<a asp-page="/Profile" asp-route-id="@Model.Id">@Model.UserName</a>

Blog/Pages/Shared/_ProfileImage.cshtml
@model ProfileImageModel

@{
    var profileImage = Url.AbsoluteContent(Model.RelativeUri ?? "~/images/ProfileDefaultImage.jpg");
    <img src="@profileImage" class="rounded-circle" height="100" width="100" />
}