Blog/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Blog.Misc;
using Blog.Models;
using Blog.Pages.Account;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Utilities;
using Utilities.Extensions;

namespace Blog.Controllers
{
    public class AccountController : ControllerBase
    {
        public AccountController(ServiceLocator serviceProvider) : base(serviceProvider)
        {
        
        }

        [HttpGet()]
        public async Task<IActionResult> Logout()
        {
            await S.Permissions.ValidateLogoutAsync();

            var currenUser = await S.UserManager.GetUserAsync(User);
            await S.SignInManager.SignOutAsync();
            if (currenUser != null)
            {
                await S.Repository.AddUserActionAsync(currenUser, new UserAction(ActionType.SIGNED_OUT, currenUser));
                await S.Db.SaveChangesAsync();
            }

            return RedirectToPage("/Index");
        }

        [HttpGet()]
        public async Task<IActionResult> UnbanAsync([Required]string userId)
        {
            if (ModelState.IsValid)
            {
                await S.Banning.UnbanAsync(userId);

                LayoutModel.AddMessage($"User has been unbanned");

                return Redirect(S.History.GetLastURL());
            }
            else
            {
                throw new Exception();
            }
        }

        [HttpGet()]
        public async Task BanForeverAsync([Required]string userId, string reason)
        {
            if (ModelState.IsValid)
            {
                var targetUser = await S.UserManager.FindByIdAsync(userId);
                await S.Permissions.ValidateBanUserAsync(targetUser);
                await S.Banning.BanForeverAsync(targetUser, reason);
            }
            else
            {
                throw new Exception();
            }
        }

        [HttpGet()]
        public async Task<IActionResult> ApplyActivationLinkAsync([Required]string token)
        {
            if (ModelState.IsValid)
            {
                var tokenData = await S.ActivationLinks.ParseAsync(token);
                if (tokenData.Validity != TokenValidity.VALID)
                {
                    return reportError(tokenData.Validity.GetEnumValueDescription());
                }

                var role = "";
                switch (tokenData.Data.Action)
                {
                    case ActivationLinkAction.REGISTER_AS_OWNER:
                        role = Roles.ADMINISTRATOR;
                        break;
                    case ActivationLinkAction.REGISTER_AS_MODERATOR:
                        role = Roles.MODERATOR;
                        break;

                    default:
                        throw new NotSupportedException();
                }

                if (User.Identity.IsAuthenticated)
                {
                    await Logout();
                }
                S.MutatorsManager.RegistrationRole = role;
                await S.ActivationLinks.MarkAsUsedOrExpiredAsync(token);
                return RedirectToPage("/Account/Register");
            }
            else
            {
                return reportError("Bad arguments");
            }
        }

        [HttpGet()]
        public async Task<IActionResult> ConfirmAsync([Required]string token)
        {
            if (ModelState.IsValid)
            {
                var tokenData = await S.ConfirmationLinks.ParseAsync(token);
                if (tokenData.Validity != TokenValidity.VALID)
                {
                    return reportError(tokenData.Validity.GetEnumValueDescription());
                }

                IActionResult view = null;
                switch (tokenData.Data.Operation)
                {
                    case AccountOperation.EMAIL_CONFIRMATION:
                        view = await confirmEmail(tokenData.Data.Target);
                        break;
                    case AccountOperation.PASSWORD_RESET:
                        view = await generateAndSendNewPasswordAsync(tokenData.Data.Target);
                        break;
                    case AccountOperation.EMAIL_CHANGE:
                        view = await changeEMail(tokenData.Data.Target, tokenData.Data.Argument);
                        break;

                    default:
                        throw new NotSupportedException();
                }

                await S.ConfirmationLinks.MarkAsUsedOrExpiredAsync(token);
                
                return view;
            }
            else
            {
                return reportError("Bad arguments");
            }
        }
        async Task<IActionResult> changeEMail(User user, string arguments)
        {
            if (arguments == null)
            {
                return reportError("Bad arguments");
            }
            else if (await S.Utilities.GetCurrentUserModelOrThrowAsync() != user)
            {
                return reportError("You should log in in order this link to work");
            }
            else
            {
                var newEmail = arguments;
                user.Email = newEmail;
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.EMAIL_CHANGED, user));
                await S.Db.SaveChangesAsync();

                LayoutModel.AddMessage($"Email has been changed to {newEmail}");

                return RedirectToPage("/Account/Profile");
            }
        }
        async Task<IActionResult> confirmEmail(User user)
        {
            if (user.EmailConfirmed)
            {
                return RedirectToPage("/Index");
            }
            else if (await S.Utilities.GetCurrentUserModelOrThrowAsync() != user)
            {
                return reportError("You should be signed in in order this link to work");
            }
            else
            {
                await S.Db.Entry(user).Reference(u => u.Status).LoadAsync();
                user.EmailConfirmed = true;
                user.Status.State = ProfileState.ACTIVE;
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.EMAIL_CONFIRMED, user));
                await S.Db.SaveChangesAsync();

                LayoutModel.AddMessage("Email has been confirmed!");

                return RedirectToPage("/Index");
            }
        }
        async Task<IActionResult> generateAndSendNewPasswordAsync(User user)
        {
            var newPassword = 3.Times(_ => Global.Random.NextENWord().Capitalize()).Aggregate("");
            var isSent = await S.EMail.TrySendMessageAsync(user, "Password reset", "New password", $@"Your new password is: {newPassword}
Please delete this message so that nobody can see it");
            if (isSent)
            {
                user.PasswordHash = S.UserManager.PasswordHasher.HashPassword(user, newPassword);
                var result = await S.UserManager.UpdateAsync(user);
                await S.SignInManager.SignOutAsync();
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.PASSWORD_RESET, user));
                await S.Db.SaveChangesAsync();

                LayoutModel.AddMessage("New password has been sent to your E-Mail");

                return RedirectToPage("/Account/Login");
            }
            else
            {
                return reportError("Could not send the E-Mail");
            }
        }
        IActionResult reportError(string message)
        {
            LayoutModel.AddMessage(message);

            return RedirectToPage("/Index");
        }
    }
}

Blog/Pages/Account/BanConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Utilities.Extensions;

namespace Blog.Pages.Account
{
    public class BanConfirmationModel : PageModelBase
    {
        [BindProperty()]
        public string UserId { get; set; }
        [BindProperty, DataType(DataType.Date), Required]
        public DateTime BannedTill { get; set; } = DateTime.UtcNow;
        [BindProperty, DataType(DataType.MultilineText), MinLength(10), Required]
        public string Reason { get; set; }

        public BanConfirmationModel(ServiceLocator serviceProvider) : base(serviceProvider)
        {

        }

        public async Task OnGetAsync([Required]string id)
        {
            UserId = id;
            var targetUser = await S.UserManager.FindByIdAsync(id);
            await S.Permissions.ValidateBanUserAsync(targetUser);
        }

        public async Task<IActionResult> OnPostBanAsync()
        {
            if (ModelState.IsValid)
            {
                if (BannedTill.ToUniversalTime() <= DateTime.UtcNow)
                {
                    ModelState.AddModelError("", $"Selected date is less than current");

                    return Page();
                }
                else
                {
                    var targetUser = await S.UserManager.FindByIdAsync(UserId);
                    await S.Permissions.ValidateBanUserAsync(targetUser);
                    await S.Banning.BanAsync(targetUser, BannedTill, Reason);
                    LayoutModel.AddMessage($"User \"{targetUser.UserName}\" has been banned");

                    return Redirect("/Index");
                }
            }
            else
            {
                return Page();
            }
        }
    }
}

Blog/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Controllers;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Utilities;
using Utilities.Extensions;

namespace Blog.Pages.Account
{
    public class ConfirmEMailModel : PageModelBase
    {
        public User UserModel { get; private set; }
        public bool IsConfirmationLinkSent { get; private set; }

        public ConfirmEMailModel(ServiceLocator services) : base(services)
        {

        }

        public async Task<IActionResult> OnGetAsync()
        {
            UserModel = await S.Utilities.GetCurrentUserModelOrThrowAsync();

            if (UserModel.EmailConfirmed)
            {
                return Page();
            }
            else
            {
                var confirmationUrl = await S.ConfirmationLinks.GetEMailConfirmationLinkAsync(UserModel);
                var message = $@"Hi {UserModel.UserName}!

Please follow this link to complete the registration: {confirmationUrl}";
                IsConfirmationLinkSent = await S.EMail.TrySendMessageAsync(UserModel, "Registration", "EMail confirmation", message);

                return Page();
            }
        }
    }
}

Blog/Pages/Account/EmailChange.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Controllers;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blog.Pages.Account
{
    public class EmailChangeModel : PageModelBase
    {
        [BindProperty, Required, DataType(DataType.Password)]
        public string Password { get; set; }
        [BindProperty, Required, DataType(DataType.EmailAddress)]
        public string NewEMail { get; set; }

        public EmailChangeModel(ServiceLocator services) : base(services)
        {

        }

        public async Task OnGet()
        {
            var user = await S.Utilities.GetCurrentUserModelOrThrowAsync();
            await S.Permissions.ValidateChangeEmailAsync(user);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                autoSaveDbChanges = true;

                var user = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                await S.Permissions.ValidateChangeEmailAsync(user);

                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.EMAIL_CHANGING, user));

                if (NewEMail.ToUpperInvariant() == user.NormalizedEmail)
                {
                    ModelState.AddModelError("", "Enter new e-mail");

                    return Page();
                }
                var isPasswordValid = await S.UserManager.CheckPasswordAsync(user, Password);
                if (!isPasswordValid)
                {
#warning security problem
                    ModelState.AddModelError("", "Incorrect password");

                    return Page();
                }

                var confirmationLink = await S.ConfirmationLinks.GetEMailChangeConfirmationLinkAsync(user, NewEMail);
                var isSent = await S.EMail.TrySendMessageAsync(user, "E-Mail change", "Administration", $@"You are trying to change profile e-mail.
Current e-mail: {user.Email}
New e-mail: {NewEMail}
Follow this link to finish the operation: {confirmationLink}");

                if (isSent)
                {
                    LayoutModel.AddMessage($"Conformation link has been send to {NewEMail}");

                    return Redirect(S.History.GetLastURL());
                }
                else
                {
                    LayoutModel.AddMessage("Couldn't send confirmation link. Try later.");

                    return Page();
                }
            }
            else
            {
                return Page();
            }
        }
    }
}

Blog/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Blog.Pages.Account
{
    public class LoginModel : PageModelBase
    {
        [BindProperty]
        [Required(ErrorMessage = "Login is required")]
        public string Login { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Password is required"), DataType(DataType.Password)]
        public string Password { get; set; }

        public LoginModel(ServiceLocator serviceProvider) : base(serviceProvider)
        {

        }

        public async Task<IActionResult> OnGetAsync(string userName)
        {
            if (User.Identity.IsAuthenticated)
            {
                await S.SignInManager.SignOutAsync();
            }

            Login = userName;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await S.Db.Users
                    .FirstOrDefaultAsync(u => u.UserName == Login);
                if (user == null)
                {
                    ModelState.AddModelError("", "This login is not registered");

                    return Page();
                }
                else
                {
                    var result = await S.SignInManager.PasswordSignInAsync(user, Password, true, false);
                    if (result.Succeeded)
                    {
                        await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.SIGNED_IN, user));
                        await S.Db.SaveChangesAsync();

                        return RedirectToPage("/Index");
                    }
                    else
                    {
                        await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.SIGN_IN_FAILED, user));
                        await S.Db.SaveChangesAsync();

                        ModelState.AddModelError("", "Login or password is not valid");

                        return Page();
                    }
                }
            }
            else
            {
                return Page();
            }
        }
    }
}

Blog/Pages/Account/BanConfirmation.cshtml
@page
@model Blog.Pages.Account.BanConfirmationModel
@{
    ViewData["Title"] = "Ban confirmation";
}

<div class="form-sm">
    <form method="post" class="container" asp-page-handler="Ban">
        <input type="hidden" asp-for="UserId" />

        <h2>Ban confirmation</h2>

        <div class="form-group">
            <label>Duration</label>
            <input class="form-control" asp-for="BannedTill" />
            <span class="text-danger" asp-validation-for="BannedTill"></span>
        </div>
        <div class="form-group">
            <label>Reason</label>
            <textarea class="form-control" asp-for="Reason" placeholder="Reason"></textarea>
            <span class="text-danger" asp-validation-for="Reason"></span>
        </div>

        <div asp-validation-summary="ModelOnly"></div>

        <button type="submit" class="btn btn-primary">Apply</button>
    </form>
</div>

Blog/Pages/Account/ConfirmEmail.cshtml
@page
@model Blog.Pages.Account.ConfirmEMailModel
@{
    ViewData["Title"] = "E-Mail confirmation";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container container-main">
    @if (Model.UserModel.EmailConfirmed)
    {
        <div>
            Your E-Mail is now confirmed. You can post and comment now!
        </div>
        <div>
            <a asp-page="/Index">Go home</a>
        </div>
    }
    else
    {
        @if (Model.IsConfirmationLinkSent)
        {
            <h2>Almost done!</h2>

            <div>
                We've sent confirmation link to your e-mail
            </div>
        }
        else
        {
            <div>We couldn't send confirmation link to your email</div>
            <div><a asp-page="/Account/ConfirmEMail">Send again</a></div>
        }
    }
</div>

Blog/Pages/Account/EmailChange.cshtml
@page
@model Blog.Pages.Account.EmailChangeModel
@{
    ViewData["Title"] = "Email change";
}

<div class="form-sm">
    <form method="post" class="container">

        <h2>Email change</h2>

        <div class="form-group">
            <label>Password</label>
            <input class="form-control" asp-for="Password" />
            <span class="text-danger" asp-validation-for="Password"></span>
        </div>
        <div class="form-group">
            <label>New E-Mail</label>
            <input class="form-control" asp-for="NewEMail" />
            <span class="text-danger" asp-validation-for="NewEMail"></span>
        </div>

        <div asp-validation-summary="ModelOnly"></div>

        <button type="submit" class="btn btn-primary">Send confirmation</button>
    </form>
</div>

Blog/Pages/Account/Login.cshtml
@page
@model Blog.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="form-sm">
    <form method="post" class="container">
        <h2>Login</h2>

        <div class="form-group">
            <label for="exampleInputEmail1">Login</label>
            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter login" asp-for="Login" />
            <span class="text-danger" asp-validation-for="Login"></span>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter password" asp-for="Password">
            <span class="text-danger" asp-validation-for="Password"></span>
        </div>

        <div class="form-group">
            <a asp-page="/Account/PasswordRestore">Forgot password?</a>
        </div>

        <button type="submit" class="btn btn-primary">Log me in!</button>
    </form>
</div>

Blog/Pages/Account/PasswordChange.cshtml
@page
@model Blog.Pages.Account.PasswordChangeModel
@{
    ViewData["Title"] = "Password change";
}

<div class="form-sm">
    <form method="post" class="container">
        <h2>Password change</h2>

        <div class="form-group">
            <label>Current password</label>
            <input class="form-control" asp-for="CurrentPassword" />
            <span class="text-danger" asp-validation-for="CurrentPassword"></span>
        </div>
        <div class="form-group">
            <label>New password</label>
            <input class="form-control" asp-for="NewPassword" />
            <span class="text-danger" asp-validation-for="NewPassword"></span>
        </div>
        <div class="form-group">
            <label>New password confirmation</label>
            <input class="form-control" asp-for="NewPasswordConfirmation" />
            <span class="text-danger" asp-validation-for="NewPasswordConfirmation"></span>
        </div>

        <div asp-validation-summary="ModelOnly"></div>

        <button type="submit" class="btn btn-primary">Change password</button>
    </form>
</div>

Blog/Pages/Account/PasswordRestore.cshtml
@page
@model Blog.Pages.Account.PasswordRestoreModel
@{
    ViewData["Title"] = "Password reset";
}

<div class="form-sm">
    <form method="post">
        <h2>Password reset</h2>

        <span class="form-caption">Enter your profile name and we will send you new password on your E-Mail provided during registration</span>

        <div class="form-group">
            <label>User name</label>
            <input class="form-control" asp-for="UserName" placeholder="User name" />
            <span class="text-danger" asp-validation-for="UserName"></span>
        </div>

        <div class="form-group">
            <button class="btn btn-primary" type="submit">Send new password</button>
        </div>
    </form>
</div>

Blog/Pages/Account/ProfileEdit.cshtml
@page
@model Blog.Pages.Account.ProfileEditModel

<div class="form-sm">
    <form method="post" class="container" enctype="multipart/form-data">
        <input type="hidden" asp-for="EditUserId" value="@Model.EditUserId" />

        <h2>Profile edit</h2>

        <div class="form-group">
            <label>Profile image</label>
            <input type="file" class="form-control-file" asp-for="ProfileImage" accept="image/x-png,image/jpeg"/>
            <span class="text-danger" asp-validation-for="ProfileImage"></span>
        </div>
        <div class="form-group">
            <label>About</label>
            <textarea rows="3" class="form-control" asp-for="About" placeholder="Information about you">@Model.About</textarea>
            <span class="text-danger" asp-validation-for="About"></span>
        </div>

        <div asp-validation-summary="ModelOnly"></div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

Blog/Pages/Account/Register.cshtml
@page
@model Blog.Pages.Account.RegisterModel
@{
    ViewData["Title"] = "Registration";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="form-sm">
    <form method="post">
        <h2>Registration</h2>

        <input type="hidden" asp-for="@Model.RegistrationRole" value="@Model.RegistrationRole"/>

        @if (Model.RegistrationRole != Roles.USER)
        {
            <span>You will be registered as @Model.RegistrationRole</span>
        }

        <div class="form-group">
            <label>User name</label>
            <input class="form-control" asp-for="Username" />
            <span class="text-danger" asp-validation-for="Username"></span>
        </div>

        <div class="form-group">
            <label>E-Mail</label>
            <input class="form-control" asp-for="EMail" />
            <span class="text-danger" asp-validation-for="EMail"></span>
        </div>

        <div class="form-group">
            <label>Password</label>
            <input class="form-control" asp-for="Password" />
            <span class="text-danger" asp-validation-for="Password"></span>
        </div>

        <div class="form-group">
            <label>Confirm password</label>
            <input class="form-control" asp-for="ConfirmPassword" />
            <span class="text-danger" asp-validation-for="ConfirmPassword"></span>
        </div>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <button class="btn btn-primary" type="submit">Register</button>
        </div>
    </form>
</div>