Blog/Controllers/CommentaryController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Attributes;
using Blog.Misc;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;

namespace Blog.Controllers
{
    [Authorize]
    public class CommentaryController : ControllerBase
    {
        public const int MAX_COMMENTARY_LENGTH = 500;
        public const int MIN_COMMENTARY_LENGTH = 10;
        public const int MIN_EDIT_REASON_LENGTH = 10;
        public const int MAX_EDIT_REASON_LENGTH = 100;

        public CommentaryController(ServiceLocator serviceProvider) : base(serviceProvider)
        {

        }

        [HttpGet, AJAX]
        public async Task<IActionResult> GetCommentaryEditAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var commentary = await S.Db.Commentaries.AsNoTracking()
                    .Include(c => c.Author)
                    .FirstOrDefaultAsync(c => c.Id == id);
                var model = new CommentaryEditinigModel()
                {
                    Author = commentary.Author.UserName,
                    AuthorId = commentary.Author.Id,
                    Body = commentary.Body,
                    CommentaryId = commentary.Id,
                };

                return PartialView(Partials.COMMENTARY_EDIT, model);
            }
            else
            {
                throw new Exception();
            }
        }

        [HttpPost, AJAX]
        public async Task<IActionResult> UpdateCommentaryAsync([Required]CommentaryEditinigModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await S.UserManager.GetUserAsync(User);
                var commentary = await S.Db.Commentaries
                    .Include(c => c.Post)
                    .FirstOrDefaultAsync(c => c.Id == model.CommentaryId);
                await S.Permissions.ValidateEditCommentaryAsync(commentary);

                var user = await S.UserManager.GetUserAsync(User);
                commentary.Body = model.Body;
                commentary.Edits.Add(new CommentaryEdit(user, model.Reason, DateTime.UtcNow));
                await S.Repository.AddUserActionAsync(currentUser, new UserAction(ActionType.COMMENTARY_EDIT, commentary));
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(commentary.Post.Id);
            }
            else
            {
                if (model.Reason == null)
                {
                    LayoutModel.AddMessage("Edit reason is required");
                }
                else if (model.Body == null)
                {
                    LayoutModel.AddMessage("Commentary body is required");
                }
                else
                {
                    throw new Exception();
                }
            }

            return Redirect(S.History.GetLastURL());
        }

        [HttpGet, AJAX]
        public async Task<IActionResult> DeleteCommentaryAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var commentary = await S.Db.Commentaries
                    .Include(c => c.Post)
                    .FirstOrDefaultAsync(c => c.Id == id);
                await S.Permissions.ValidateDeleteCommentaryAsync(commentary);
               
                var user = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.COMMENTARY_DELETE, commentary));
                commentary.IsDeleted = true;
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(commentary.Post.Id);

                return Redirect(S.History.GetLastURL());
            }
            else
            {
                throw new Exception();
            }
        }

        [HttpGet, AJAX]
        public async Task<IActionResult> RestoreCommentaryAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var commentary = await S.Db.Commentaries
                    .Include(c => c.Post)
                    .FirstOrDefaultAsync(c => c.Id == id);
                await S.Permissions.ValidateRestoreCommentaryAsync(commentary);
               
                var user = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                await S.Repository.AddUserActionAsync(user, new UserAction(ActionType.COMMENTARY_RESTORED, commentary));
                commentary.IsDeleted = false;
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(commentary.Post.Id);

                return Redirect(S.History.GetLastURL());
            }
            else
            {
                throw new Exception();
            }
        }
    }
}

Blog/Pages/AdminPanel.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Controllers;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blog.Pages
{
    public class AdminPanelModel : PageModelBase
    {
        public IEnumerable<User> Moderators { get; private set; }
        public IQueryable<ModeratorsGroup> ModeratorsGroups { get; private set; }

        public AdminPanelModel(ServiceLocator services) : base(services)
        {

        }
        
        public async Task OnGetAsync()
        {
            await S.Permissions.ValidateAccessBlogControlPanelAsync();

            Moderators = await S.UserManager.GetUsersInRoleAsync(Roles.MODERATOR);
            ModeratorsGroups = S.Db.ModeratorsGroups;
        }
    }
}

Blog/Pages/BlogControlPanel.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Controllers;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blog.Pages
{
    public class BlogControlPanelModel : PageModelBase
    {
        public IEnumerable<User> Moderators { get; private set; }

        public BlogControlPanelModel(ServicesProvider services) : base(services)
        {

        }
        
        public async Task OnGetAsync()
        {
            await S.Permissions.ValidateAccessBlogControlPanelAsync();
            Moderators = await S.UserManager.GetUsersInRoleAsync(Roles.MODERATOR);
        }
    }
}

Blog/Pages/Post.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Attributes;
using Blog.Middlewares;
using Blog.Middlewares.CachingMiddleware.Policies;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Utilities.Extensions;
using Utilities.Types;

namespace Blog.Pages
{
    public class PostModel : PageModelBase
    {
        public Models.PostModel Post { get; private set; } 

        [BindProperty]
        public CommentaryCreateModel NewCommentary { get; set; }

        public PostModel(ServiceLocator serviceProvider) : base(serviceProvider)
        {
            NewCommentary = new CommentaryCreateModel();
        }

        [ServerResponseCacheHandler(CacheManagerService.POST_GET_CACHE_KEY)]
        public static async Task HandelCachedOnGetAsync(CacheScope scope)
        {
            var services = scope.ServiceProvider.GetService<ServiceLocator>();
            var viewStatistics = scope.RequestData.To<IViewStatistic[]>();

            await updateViewStatisticAsync(services.DbUpdator, false, viewStatistics);
        }
         
        [ServerResponseCache(3 * 60, CachePolicy.UNAUTHENTICATED_USER_SCOPED, CacheManagerService.POST_GET_CACHE_KEY)]
        public async Task<IActionResult> OnGetAsync([Required]int id)
        {
            if (ModelState.IsValid)
            {
                var post = await S.Db.Posts
                    .AsNoTracking()
                    .Include(p => p.Author)
                    .ThenInclude(a => a.Profile)
                    .Include(p => p.ModerationInfo)
                    .Include(p => p.ViewStatistic)
                    .Include(p => p.Edits)
                    .ThenInclude(e => e.Author)
                    .FirstOrDefaultAsync(p => p.Id == id);
                if (post == null)
                {
                    throw new NotFoundException();
                }
                else
                {
                    await S.Permissions.ValidateViewPostAsync(post);

                    var commentaries = await S.Repository.GetCommentaryModelsAsync(
                            S.Db.Commentaries
                            .AsNoTracking()
                            .Where(c => c.Post.Id == id));
                    Post = new Models.PostModel()
                    {
                        Author = post.Author.UserName,
                        AuthorId = post.Author.Id,
                        Body = post.Body,
                        PostId = post.Id,
                        CreationTime = post.CreationTime,
                        Title = post.Title,
                        CommentarySectionModel = new CommentarySectionModel()
                        {
                            Commentaries = commentaries.ToArray()
                        },
                        Edits = post.Edits.Select(e => new Models.PostEditModel()
                        {
                            Author = e.Author.UserName,
                            Reason = e.Reason,
                            AuthorId = e.Author.Id,
                            EditTime = e.EditTime
                        }).ToArray(),
                        AuthorBiography = post.Author.Profile.About,
                        IsAuthentificated = S.HttpContext.User?.Identity?.IsAuthenticated ?? false,
                        TotalViews = post.ViewStatistic.TotalViews,
                        ModerationState = post.ModerationInfo.State,
                        AuthorProfileImage = new ProfileImageModel()
                        {
                            RelativeUri = post.Author.Profile.Image
                        },
                        IsDeleted = post.IsDeleted,
                        DeleteReason = post.DeleteReason,

                        CanAddCommentary = await S.Permissions.CanAddCommentaryAsync(post),
                        CanDelete = await S.Permissions.CanDeletePostAsync(post),
                        CanRestore = await S.Permissions.CanRestorePostAsync(post),
                        CanReport = await S.Permissions.CanReportAsync(post),
                        CanReportViolation = await S.Permissions.CanReportViolationAsync(post),
                        CanEdit = await S.Permissions.CanEditPostAsync(post),
                        CanMarkAsModerated = await S.Permissions.CanMarkAsModeratedAsync(post),
                        CanMarkAsNotPassedModeration = await S.Permissions.CanMarkAsNotPassedModerationAsync(post),
                    };

                    var viewStatistics = new Enumerable<IViewStatistic>
                        {
                            post.ViewStatistic,
                            commentaries.Select(c => c.ViewStatistic),
                        }.ToArray();

                    await S.CacheManager.CacheManager.SetRequestDataAsync(viewStatistics);
                    await updateViewStatisticAsync(S.DbUpdator, S.HttpContext.User?.Identity?.IsAuthenticated ?? false, viewStatistics);

                    NewCommentary.PostId = id;

                    return Page();
                }
            }
            else
            {
                throw new Exception();
            }
        }

        static async Task updateViewStatisticAsync(DbEntitiesUpdateService updateService, bool isUserRegistered, IViewStatistic[] viewStatistics)
        {
            foreach (var vs in viewStatistics)
            {
                await updateService.UpdateViewStatisticAsync(isUserRegistered, vs);
            }
        }

        [HttpPost]
        public async Task<IActionResult> OnPostAddCommentaryAsync()
        {
            if (ModelState.IsValid)
            {
                var post = await S.Db.Posts
                    .Include(p => p.ModerationInfo)
                    .FirstOrDefaultAsync(p => p.Id == NewCommentary.PostId);
                await Permissions.ValidateAddCommentaryAsync(post);

                var currentUser = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                var comment = new Commentary(
                        currentUser,
                        DateTime.UtcNow,
                        post,
                        NewCommentary.Body);
                S.Db.Commentaries.Add(comment);
                await S.Repository.AddUserActionAsync(currentUser, new UserAction(ActionType.COMMENTARY_ADDED, comment));
                await S.Db.SaveChangesAsync();
                await S.CacheManager.ResetPostPageCacheAsync(post.Id);

                return RedirectToPage("/Post", new { id = NewCommentary.PostId });
            }
            else
            {
                return Redirect(S.History.GetLastURL());
            }
        }
    }
}

Blog/Pages/ViolationReport.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Blog.Models;
using Blog.Services;
using DBModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Blog;
using Microsoft.EntityFrameworkCore;

namespace Blog.Pages
{
    public class ViolationReportModel : PageModelBase
    {
        [Required, MinLength(3), MaxLength(500), BindProperty()]
        public string Description { get; set; }

        [BindProperty]
        public int? CommentaryReportObjectId { get; set; }
        [BindProperty]
        public int? PostReportObjectId { get; set; }
        [BindProperty]
        public int? ProfileReportObjectId { get; set; }

        public ViolationReportModel(ServiceLocator services) : base(services)
        {

        }

        public void OnGetCommentary([Required]int id)
        {
            CommentaryReportObjectId = id;
        }

        public void OnGetPost([Required]int id)
        {
            PostReportObjectId = id;
        }

        public void OnGetProfile([Required]int id)
        {
            ProfileReportObjectId = id;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                IReportable reportObject;
                if (CommentaryReportObjectId != null)
                {
                    reportObject = await S.Db.Commentaries
                        .Include(o => o.Author)
                        .FirstAsync(c => c.Id == CommentaryReportObjectId.Value);
                }
                else if (PostReportObjectId != null)
                {
                    reportObject = await S.Db.Posts
                        .Include(o => o.Author)
                        .FirstAsync(c => c.Id == PostReportObjectId.Value);
                }
                else if (ProfileReportObjectId != null)
                {
                    reportObject = await S.Db.ProfilesInfos
                        .Include(o => o.Author)
                        .FirstAsync(c => c.Id == ProfileReportObjectId.Value);
                }
                else
                {
                    throw new NotSupportedException();
                }

                await Permissions.ValidateReportViolationAsync(reportObject);
                var currentUser = await S.Utilities.GetCurrentUserModelOrThrowAsync();
                var violation = new Violation(currentUser, reportObject.Author, reportObject, Description);
                var action = new UserAction(ActionType.VIOLATION_REPORTED, reportObject) 
                {
                    Author = currentUser 
                };
                S.Db.UserRuleViolations.Add(violation);
                S.Db.UsersActions.Add(action);
                await S.Db.SaveChangesAsync();

                LayoutModel.AddMessage("Violation report has been submitted");

                return Redirect(S.History.GetLastURL());
            }
            else
            {
                return Page();
            }
        }
    }
}

Blog/Pages/Commentary.cshtml
@page
@model Blog.Pages.CommentaryModel
@{
    ViewData["Title"] = "Commentary";
}
<div class="container container-main">
    <div class="row">
        <div class="col">
            <partial name="@Partials.COMMENTARY" model="Model.Commentary" />

            @if (await Model.Permissions.CanSeeServiceInformationAsync())
            {
                <hr />

                <h4>Info</h4>
                var parameters = new Dictionary<string, object>()
                {
                    { "Id", Model.Commentary.CommentaryId },
                    { "Registred users views", Model.Commentary.ViewStatistic.RegisteredUserViews },
                    { "Total views", Model.Commentary.ViewStatistic.TotalViews },
                };

                foreach (var parameter in parameters)
                {
                    <div>@parameter.Key: @parameter.Value</div>
                }
            }
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_CommentartyScripts" />
}

Blog/Pages/Index.cshtml
@page "{handler?}/{id?}"
@model Blog.Pages.IndexModel

@{
    ViewData["Title"] = "Home";
}

<div class="jumbotron jumbotron-fluid mb-0">
    <div class="container text-center">
        <h1 class="display-4">The Blog</h1>
        <p class="lead">Or simply the first ASP .NET Core 2.2 web project :)</p>
    </div>
</div>

<div class="container container-main">
    <div class="row">
        <div class="col">
            @if (Model.SearchQuery != null)
            {
                <div class="mt-3">
                    <h3 class="mb-0">Search results for "@Model.SearchQuery" | <a asp-page="Index" asp-route-pageIndex="0">Reset</a></h3>
                    <span class="text-muted">@Model.NumOfSearchResults entries found</span>
                </div>
            }

            @foreach (var post in Model.Posts)
            {
                <div class="post-preview mt-4">
                    <h4 class="font-weight-normal">
                        <a asp-page="/Post" asp-route-id="@post.PostId">@post.Title</a>
                    </h4>
                    @Html.Raw(post.BodyPreview)
                    <h6 class="font-weight-normal text-secondary">
                        Written by <a asp-page="/Account/Profile" asp-route-id="@post.AuthorId">@post.Author</a>

                        <span style="float:right">@post.CreationTime.ToString("dd.MM.yyyy")</span>
                    </h6>
                </div>
            }
        </div>
    </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        @{
            const int MAX = IndexModel.NUM_OF_POSTS_ON_PAGE;
            const int SIDE_LENGTH = (MAX - 1) / 2;
            var addStartElipsis = Model.CurrentPage - SIDE_LENGTH - 1 > 0;
            var addEndElipsis = Model.NumOfPages - 1 - (Model.CurrentPage + SIDE_LENGTH) > 1;
            IndexPageButtonModel model = null;
        }

        <li class="page-item@((Model.CurrentPage > 0).Ternar("", " disabled"))">
            @{ model = new IndexPageButtonModel(Model.CurrentPage - 1, Model.SearchQuery, "&laquo;"); }
            <partial name="@Partials.INDEX_PAGE_BUTTON" model="model" />
        </li>
        <li class="page-item @GetPageNavClass(0)">
            <partial name="@Partials.INDEX_PAGE_BUTTON" model="new IndexPageButtonModel(0, Model.SearchQuery, 1.ToString())" />
        </li>
        @if (addStartElipsis)
        {
            <li class="page-item">
                <a href="" class="page-link">...</a>
            </li>
        }
        @foreach (var i in MAX.Range().Select(i => i + Model.CurrentPage - SIDE_LENGTH).Where(i => i < Model.NumOfPages - 1).SkipNegative())
        {
            <li class="page-item @GetPageNavClass(i)">
                <partial name="@Partials.INDEX_PAGE_BUTTON" model="new IndexPageButtonModel(i, Model.SearchQuery, (i + 1).ToString())" />
            </li>
        }
        @if (addEndElipsis)
        {
            <li class="page-item">
                <a href="" class="page-link no-redirect">...</a>
            </li>
        }
        @if (Model.NumOfPages > 1)
        {
            <li class="page-item @GetPageNavClass(Model.NumOfPages.Add(-1))">
                <partial name="@Partials.INDEX_PAGE_BUTTON" model="new IndexPageButtonModel(Model.NumOfPages.Add(-1), Model.SearchQuery, Model.NumOfPages.ToString())" />
            </li>
        }
        <li class="page-item@((Model.CurrentPage < Model.NumOfPages - 1).Ternar("", " disabled"))">
            @{ model = new IndexPageButtonModel(Model.CurrentPage + 1, Model.SearchQuery, "&raquo;"); }
            <partial name="@Partials.INDEX_PAGE_BUTTON" model="model" />
        </li>
    </ul>
</nav>

@functions{
    public string GetPageNavClass(int pageIndex)
    {
        var cssClass = pageIndex == Model.CurrentPage
            ? "active"
            : "";
        return cssClass;
    }
}

Blog/Pages/MarkAsNotPassedModeration.cshtml
@page
@model Blog.Pages.MarkAsNotPassedModerationModel

<div class="form-sm">
    <form method="post">
        <input type="hidden" asp-for="PostId" value="@Model.PostId" />

        <h2>Moderation</h2>

        <div class="form-group">
            <label>Post will be marked as not moderated</label>
            <textarea asp-for="Reason" class="form-control" placeholder="What was wrong?"></textarea>
            <span asp-validation-for="Reason" class="text-danger"></span>
        </div>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <button class="btn btn-primary" type="submit">Mark as not moderated</button>
    </form>
</div>

Blog/Pages/Post.cshtml
@page "{id:int}"
@model Blog.Pages.PostModel

@{
    ViewData["Title"] = Model.Post.Title;
}

@section Styles
{
    <link rel="stylesheet" type="text/css" href="~/css/prism.css" />
}

<div class="container container-main">
    <div class="row">
        <div class="col">
            <h2 class="font-weight-normal">
                <span>@Model.Post.Title</span>
                <span include-if="Model.Post.CanEdit">| <a asp-page="/PostEdit" asp-route-id="@Model.Post.PostId">Edit</a></span>
                <span include-if="Model.Post.CanReport" class="btn-report">| <a class="no-redirect" href="" onclick="reportPost(this, @Model.Post.PostId)">Report</a></span>
                <span include-if="Model.Post.CanReportViolation">| <a asp-page="/ViolationReport" asp-page-handler="Post" asp-route-id="@Model.Post.PostId">Report violation</a></span>
                <span include-if="Model.Post.CanMarkAsModerated">| <a class="operation-primary" asp-controller="@nameof(ModerationController).GetController()" asp-action="@nameof(ModerationController.MarkPostAsModeratedAsync)" asp-route-id="@Model.Post.PostId">Mark as moderated</a></span>
                <span include-if="Model.Post.CanMarkAsNotPassedModeration">| <a class="operation-danger" asp-page="/MarkAsNotPassedModeration" asp-route-id="@Model.Post.PostId">Mark as not moderated</a></span>
                <span include-if="Model.Post.CanDelete">| <a class="operation-danger" asp-page="/PostDeleteConfirmation" asp-route-id="@Model.Post.PostId">Delete</a></span>
                <span include-if="Model.Post.CanRestore">| <a class="operation-primary" asp-controller="@nameof(PostingController).GetController()" asp-action="@nameof(PostingController.UndeletePostAsync)" asp-route-id="@Model.Post.PostId">Restore</a></span>
            </h2>

            <div class="text-secondary mb-2">
                <span>Posted at @Model.Post.CreationTime.ToHoursDateString()</span>
                <span>, seen @Model.Post.TotalViews times</span>
            </div>

            <div>
                <div include-if="@Model.Post.IsDeleted" class="text-danger">
                    <div>The post has been deleted and accessible only via link</div>
                    <div>Delete reason: @Model.Post.DeleteReason</div>
                </div>
                <div include-if="Model.Post.ModerationState == ModerationState.UNDER_MODERATION" class="text-danger">Post is under moderation and accessible only via link</div>
                <div include-if="Model.Post.ModerationState == ModerationState.MODERATION_NOT_PASSED" class="text-danger">Post hasn't passed moderation. Edit to fix problems.</div>
            </div>

            <div class="my-3">
                <div class="mce-content-body text-justify" id="tinymce" data-id="Body">
                    @Html.Raw(Model.Post.Body)
                </div>
            </div>

            @foreach (var edit in Model.Post.Edits)
            {
                <div>
                    <span>Edited at @edit.EditTime.ToString("hh:mm dd.MM.yy") by <a asp-page="/Account/Profile" asp-route-id="@edit.AuthorId">@edit.Author</a></span>
                    <span>Reason: @edit.Reason</span>
                </div>
            }

            <div class="my-4">
                <div class="d-flex flex-row">
                    <div class="d-flex flex-column align-self-center mr-4">
                        <partial name="@Partials.PROFILE_IMAGE" model="Model.Post.AuthorProfileImage" />
                    </div>
                    <div class="d-flex flex-column w-100">
                        <h4>About the <a asp-page="/Account/Profile" asp-route-id="@Model.Post.AuthorId">@Model.Post.Author</a></h4>
                        <span>@(Model.Post.AuthorBiography.IsNotNullOrWhiteSpace() ? Model.Post.AuthorBiography : "No biography provided :(")</span>
                    </div>
                </div>
            </div>

            <div include-if="Model.Post.ModerationState == ModerationState.MODERATED">
                <hr class="my-1" />

                <partial name="@Partials.COMMENTARIES_SECTION" model="Model.Post.CommentarySectionModel" />

                <div include-if="Model.Post.CanAddCommentary">
                    <form method="post" class="mt-3" asp-page-handler="AddCommentary">
                        <input type="hidden" value="@Model.NewCommentary.PostId" asp-for="NewCommentary.PostId" />

                        <div class="form-group">
                            <textarea class="form-control" rows="3" placeholder="Your comment" asp-for="NewCommentary.Body"></textarea>
                            <span class="text-danger" asp-validation-for="NewCommentary.Body"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger validation-message"></div>

                        <button type="submit" class="btn btn-primary">Send</button>
                    </form>
                </div>
                <div include-if="!Model.Post.IsAuthentificated">
                    <a asp-page="/Account/Login">Login</a>
                    <span> or </span>
                    <a asp-page="/Account/Register">register</a>
                    <span> to comment</span>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_CommentartyScripts" />
    <script src="~/js/prism.js"></script>

    <script>
        @{
            var target = new ControllerAction(nameof(ReportingController), nameof(ReportingController.ReportPostAsync));
        }

        function reportPost(element, id) {
            report(element, "@target.GetURI()", id);
        }
    </script>
}

Blog/Pages/PostCreate.cshtml
@page
@model Blog.Pages.PostCreateModel
@{
    ViewData["Title"] = "Post create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container container-main">
    <div class="row">
        <div class="col">
            <form method="post">
                <h2>Post create</h2>

                <div class="form-group">
                    <label>Title</label>
                    <input class="form-control" asp-for="Title" />
                    <span class="text-danger" asp-validation-for="Title"></span>
                </div>

                <div class="form-group">
                    <label>Post body</label>
                    <textarea class="form-control rich-edit" asp-for="Body"></textarea>
                    <span class="text-danger" asp-validation-for="Body"></span>
                </div>

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <div exclude-if="await Model.Permissions.CanCreatePostsWithoutModerationAsync()" class="mb-3">The post will be checked by moderator and published if no problems are found</div>
                    <button class="btn btn-primary" type="submit">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

Blog/Pages/PostDeleteConfirmation.cshtml
@page
@model Blog.PostDeleteConfirmationModel
@{ 
    ViewData["Title"] = "Post delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="form-sm">
    <form method="post">
        <input type="hidden" asp-for="PostId" value="@Model.PostId"/>
        
        <h2>Post delete</h2>

        <div class="form-group">This action can be undone</div>

        <div class="form-group">
            <textarea class="form-control" asp-for="Reason" placeholder="What was wrong?"></textarea>
            <span class="text-danger" asp-validation-for="Reason"></span>
        </div>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <button class="btn btn-primary" type="submit">Delete</button>
        </div>
    </form>
</div>

Blog/Pages/ViolationReport.cshtml
@page
@model Blog.Pages.ViolationReportModel
@{ 
    ViewBag.Title = "Violation report";
}

<div class="form-sm">
    <form method="post">
        <input type="hidden" asp-for="CommentaryReportObjectId" />
        <input type="hidden" asp-for="PostReportObjectId" />
        <input type="hidden" asp-for="ProfileReportObjectId" />

        <h2>Violation report</h2>

        <div class="form-group">
            <label>Violation description</label>
            <textarea rows="3" class="form-control" asp-for="Description" placeholder="What was wrong?"></textarea>
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <button class="btn btn-primary" type="submit">Report</button>
    </form>
</div>